program gen_rbf_products
    ! Generate the scalar RBF parameter products consumed by fortml_kernels.
    use, intrinsic :: iso_fortran_env, only: output_unit
    use fortad, only: fad_hvp, fad_jvp, fad_result_t, fad_vjp
    implicit none

    character(len=1), parameter :: nl = achar(10)
    character(len=*), parameter :: source = &
        "function rbf_scalar(x1, x2, lv, ll) result(y)"//nl// &
        "    real(8), intent(in) :: x1, x2, lv, ll"//nl// &
        "    real(8) :: y"//nl// &
        "    y = exp(lv - 0.5d0*(x1-x2)**2*exp(-2.0d0*ll))"//nl// &
        "end function rbf_scalar"//nl
    type(fad_result_t) :: jvp, vjp, hvp
    character(len=2048) :: output, revision
    integer :: output_length, revision_length, status, unit, ios

    call get_command_argument(1, output, length=output_length, status=status)
    call get_command_argument(2, revision, length=revision_length, status=status)
    if (output_length == 0 .or. revision_length == 0) then
        write (output_unit, '(a)') &
            'usage: gen_rbf_products OUTPUT_PATH FORTAD_REVISION'
        error stop 2
    end if

    jvp = fad_jvp(source, [character(len=2) :: 'x1', 'x2', 'lv', 'll'], &
        name='fortml_rbf_jvp')
    vjp = fad_vjp(source, [character(len=2) :: 'x1', 'x2', 'lv', 'll'], &
        name='fortml_rbf_vjp')
    hvp = fad_hvp(source, [character(len=2) :: 'x1', 'x2', 'lv', 'll'], &
        name='fortml_rbf_hvp')
    if (.not. (jvp%ok .and. vjp%ok .and. hvp%ok)) then
        write (output_unit, '(a)') 'gen_rbf_products: FortAD generation failed'
        if (.not. jvp%ok) write (output_unit, '(a)') 'JVP: '//jvp%message
        if (.not. vjp%ok) write (output_unit, '(a)') 'VJP: '//vjp%message
        if (.not. hvp%ok) write (output_unit, '(a)') 'HVP: '//hvp%message
        error stop 1
    end if

    open (newunit=unit, file=trim(output(:output_length)), status='replace', &
        action='write', iostat=ios)
    if (ios /= 0) then
        write (output_unit, '(a)') 'gen_rbf_products: cannot write output'
        error stop 1
    end if
    write (unit, '(a)') '! Generated by FortAD. Do not edit.'
    write (unit, '(a)') '! Generator: gen_rbf_products'
    write (unit, '(a)') '! FortAD revision: '//trim(revision(:revision_length))
    write (unit, '(a)') &
        '! Regenerate with: fo exec gen_rbf_products OUTPUT_PATH FORTAD_REVISION && fo fmt OUTPUT_PATH'
    write (unit, '(a)') 'module fortml_generated_rbf_products'
    write (unit, '(a)') '    implicit none'
    write (unit, '(a)') 'contains'
    write (unit, '(a)') jvp%code
    write (unit, '(a)') vjp%code
    write (unit, '(a)') hvp%code
    write (unit, '(a)') 'end module fortml_generated_rbf_products'
    close (unit)
    write (output_unit, '(a)') &
        'gen_rbf_products: wrote '//trim(output(:output_length))
end program gen_rbf_products
