program gen_matern_products
    ! Generate parameter HVP products for the scalar Matérn kernels.
    use, intrinsic :: iso_fortran_env, only: output_unit
    use fortad, only: fad_hvp, fad_result_t
    implicit none

    character(len=1), parameter :: nl = achar(10)
    character(len=*), parameter :: source12 = &
        "function matern12_scalar(distance, lv, ll) result(y)"//nl// &
        "    real(8), intent(in) :: distance, lv, ll"//nl// &
        "    real(8) :: y, r"//nl// &
        "    r = distance*exp(-ll)"//nl// &
        "    y = exp(lv-r)"//nl// &
        "end function matern12_scalar"//nl
    character(len=*), parameter :: source32 = &
        "function matern32_scalar(distance, lv, ll) result(y)"//nl// &
        "    real(8), intent(in) :: distance, lv, ll"//nl// &
        "    real(8) :: y, r"//nl// &
        "    r = sqrt(3.0d0)*distance*exp(-ll)"//nl// &
        "    y = exp(lv)*(1.0d0+r)*exp(-r)"//nl// &
        "end function matern32_scalar"//nl
    character(len=*), parameter :: source52 = &
        "function matern52_scalar(distance, lv, ll) result(y)"//nl// &
        "    real(8), intent(in) :: distance, lv, ll"//nl// &
        "    real(8) :: y, r"//nl// &
        "    r = sqrt(5.0d0)*distance*exp(-ll)"//nl// &
        "    y = exp(lv)*(1.0d0+r+r*r/3.0d0)*exp(-r)"//nl// &
        "end function matern52_scalar"//nl
    type(fad_result_t) :: hvp12, hvp32, hvp52
    character(len=2048) :: output, revision
    integer :: output_length, revision_length, status, unit, ios

    call get_command_argument(1, output, length=output_length, status=status)
    call get_command_argument(2, revision, length=revision_length, status=status)
    if (output_length == 0 .or. revision_length == 0) then
        write (output_unit, '(a)') &
            'usage: gen_matern_products OUTPUT_PATH FORTAD_REVISION'
        error stop 2
    end if

    hvp12 = fad_hvp(source12, [character(len=8) :: 'distance', 'lv', 'll'], &
        name='fortml_matern12_hvp')
    hvp32 = fad_hvp(source32, [character(len=8) :: 'distance', 'lv', 'll'], &
        name='fortml_matern32_hvp')
    hvp52 = fad_hvp(source52, [character(len=8) :: 'distance', 'lv', 'll'], &
        name='fortml_matern52_hvp')
    if (.not. (hvp12%ok .and. hvp32%ok .and. hvp52%ok)) then
        write (output_unit, '(a)') 'gen_matern_products: FortAD generation failed'
        if (.not. hvp12%ok) write (output_unit, '(a)') 'Matern12: '//hvp12%message
        if (.not. hvp32%ok) write (output_unit, '(a)') 'Matern32: '//hvp32%message
        if (.not. hvp52%ok) write (output_unit, '(a)') 'Matern52: '//hvp52%message
        error stop 1
    end if

    open (newunit=unit, file=trim(output(:output_length)), status='replace', &
        action='write', iostat=ios)
    if (ios /= 0) then
        write (output_unit, '(a)') 'gen_matern_products: cannot write output'
        error stop 1
    end if
    write (unit, '(a)') '! Generated by FortAD. Do not edit.'
    write (unit, '(a)') '! Generator: gen_matern_products'
    write (unit, '(a)') '! FortAD revision: '//trim(revision(:revision_length))
    write (unit, '(a)') &
        '! Regenerate with: fo exec gen_matern_products OUTPUT_PATH FORTAD_REVISION && fo fmt OUTPUT_PATH'
    write (unit, '(a)') 'module fortml_generated_matern_products'
    write (unit, '(a)') '    implicit none'
    write (unit, '(a)') 'contains'
    write (unit, '(a)') hvp12%code
    write (unit, '(a)') hvp32%code
    write (unit, '(a)') hvp52%code
    write (unit, '(a)') 'end module fortml_generated_matern_products'
    close (unit)
    write (output_unit, '(a)') &
        'gen_matern_products: wrote '//trim(output(:output_length))
end program gen_matern_products
