! Generated by FortAD. Do not edit.
! Generator: gen_rbf_products
! FortAD revision: 5e1bfe0
! Regenerate with: fo exec gen_rbf_products OUTPUT_PATH FORTAD_REVISION && fo fmt OUTPUT_PATH
module fortml_generated_rbf_products
    implicit none
contains
    pure subroutine fortml_rbf_jvp(x1, x1_d, x2, x2_d, lv, lv_d, ll, ll_d, y, y_d)
        implicit none
        real(8), intent(in) :: x1
        real(8), intent(in) :: x1_d
        real(8), intent(in) :: x2
        real(8), intent(in) :: x2_d
        real(8), intent(in) :: lv
        real(8), intent(in) :: lv_d
        real(8), intent(in) :: ll
        real(8), intent(in) :: ll_d
        real(8), intent(out) :: y
        real(8), intent(out) :: y_d

        y_d = exp(lv - 0.5d0 * (x1 - x2) ** 2 * exp((-2.0d0) * ll)) * (lv_d - (0.5d0 * (2 &
            * (x1 - x2) * (x1_d - x2_d)) * exp((-2.0d0) * ll) - 0.5d0 * (x1 - x2) ** 2 * &
            exp((-2.0d0) * ll) * 2.0d0 * ll_d))
        y = exp(lv - 0.5d0 * (x1 - x2) ** 2 * exp((-2.0d0) * ll))
    end subroutine fortml_rbf_jvp

    pure subroutine fortml_rbf_vjp(x1, x2, lv, ll, y, y_b, x1_b, x2_b, lv_b, ll_b)
        implicit none
        real(8), intent(in) :: x1
        real(8), intent(in) :: x2
        real(8), intent(in) :: lv
        real(8), intent(in) :: ll
        real(8), intent(out) :: y
        real(8), intent(in) :: y_b
        real(8), intent(out) :: x1_b
        real(8), intent(out) :: x2_b
        real(8), intent(out) :: lv_b
        real(8), intent(out) :: ll_b
        real(8) :: y_v1
        real(8) :: y_v1_b
        real(8) :: fad_t1
        real(8) :: fad_t2
        real(8) :: fad_t3
        real(8) :: fad_t4
        real(8) :: fad_t5
        real(8) :: fad_t6
        real(8) :: fad_t7
        real(8) :: fad_t8
        real(8) :: fad_t9

        y = exp(lv - 0.5d0 * (x1 - x2) ** 2 * exp((-2.0d0) * ll))
        fad_t1 = y_b * exp(lv - 0.5d0 * (x1 - x2) ** 2 * exp((-2.0d0) * ll))
        lv_b = fad_t1
        fad_t2 = fad_t1 * (-1.0d0)
        fad_t5 = fad_t2 * exp((-2.0d0) * ll) * 0.5d0 * (2 * (x1 - x2))
        x1_b = fad_t5
        x2_b = fad_t5 * (-1.0d0)
        ll_b = fad_t2 * (0.5d0 * (x1 - x2) ** 2) * exp((-2.0d0) * ll) * (-2.0d0)
    end subroutine fortml_rbf_vjp

    pure subroutine fortml_rbf_hvp(x1, x1_d, x2, x2_d, lv, lv_d, ll, ll_d, y, y_d, y_b, &
            x1_b, x1_b_d, x2_b, x2_b_d, lv_b, lv_b_d, ll_b, ll_b_d)
        implicit none
        real(8), intent(in) :: x1
        real(8), intent(in) :: x1_d
        real(8), intent(in) :: x2
        real(8), intent(in) :: x2_d
        real(8), intent(in) :: lv
        real(8), intent(in) :: lv_d
        real(8), intent(in) :: ll
        real(8), intent(in) :: ll_d
        real(8), intent(out) :: y
        real(8), intent(out) :: y_d
        real(8), intent(in) :: y_b
        real(8), intent(out) :: x1_b
        real(8), intent(out) :: x1_b_d
        real(8), intent(out) :: x2_b
        real(8), intent(out) :: x2_b_d
        real(8), intent(out) :: lv_b
        real(8), intent(out) :: lv_b_d
        real(8), intent(out) :: ll_b
        real(8), intent(out) :: ll_b_d
        real(8) :: y_v1
        real(8) :: y_v1_b
        real(8) :: fad_t1
        real(8) :: fad_t1_d
        real(8) :: fad_t2
        real(8) :: fad_t2_d
        real(8) :: fad_t3
        real(8) :: fad_t4
        real(8) :: fad_t5
        real(8) :: fad_t5_d
        real(8) :: fad_t6
        real(8) :: fad_t7
        real(8) :: fad_t8
        real(8) :: fad_t9

        y_d = exp(lv - 0.5d0 * (x1 - x2) ** 2 * exp((-2.0d0) * ll)) * (lv_d - (0.5d0 * (2 &
            * (x1 - x2) * (x1_d - x2_d)) * exp((-2.0d0) * ll) - 0.5d0 * (x1 - x2) ** 2 * &
            exp((-2.0d0) * ll) * 2.0d0 * ll_d))
        y = exp(lv - 0.5d0 * (x1 - x2) ** 2 * exp((-2.0d0) * ll))
        fad_t1_d = y_b * (exp(lv - 0.5d0 * (x1 - x2) ** 2 * exp((-2.0d0) * ll)) * (lv_d - &
            (0.5d0 * (2 * (x1 - x2) * (x1_d - x2_d)) * exp((-2.0d0) * ll) - 0.5d0 * (x1 - x2) &
            ** 2 * exp((-2.0d0) * ll) * 2.0d0 * ll_d)))
        fad_t1 = y_b * exp(lv - 0.5d0 * (x1 - x2) ** 2 * exp((-2.0d0) * ll))
        lv_b_d = fad_t1_d
        lv_b = fad_t1
        fad_t2_d = fad_t1_d * (-1.0d0)
        fad_t2 = fad_t1 * (-1.0d0)
        fad_t5_d = (fad_t2_d * exp((-2.0d0) * ll) - fad_t2 * exp((-2.0d0) * ll) * 2.0d0 * &
            ll_d) * 0.5d0 * (2 * (x1 - x2)) + fad_t2 * exp((-2.0d0) * ll) * 0.5d0 * (2 * &
            (x1_d - x2_d))
        fad_t5 = fad_t2 * exp((-2.0d0) * ll) * 0.5d0 * (2 * (x1 - x2))
        x1_b_d = fad_t5_d
        x1_b = fad_t5
        x2_b_d = fad_t5_d * (-1.0d0)
        x2_b = fad_t5 * (-1.0d0)
        ll_b_d = ((fad_t2_d * (0.5d0 * (x1 - x2) ** 2) + fad_t2 * (0.5d0 * (2 * (x1 - x2) &
            * (x1_d - x2_d)))) * exp((-2.0d0) * ll) - fad_t2 * 0.5d0 * (x1 - x2) ** 2 * &
            exp((-2.0d0) * ll) * 2.0d0 * ll_d) * (-2.0d0)
        ll_b = fad_t2 * (0.5d0 * (x1 - x2) ** 2) * exp((-2.0d0) * ll) * (-2.0d0)
    end subroutine fortml_rbf_hvp

end module fortml_generated_rbf_products
