! FortSym IR nodes: 15
! FortSym compound operations: 7
! Generated by fortsym. Do not edit.
! Generator: gen_rbf_derivatives
! Generator revision: 58a0e06
! Regenerate with: fo exec gen_rbf_derivatives OUTPUT_PATH FORTSYM_REVISION

subroutine fortml_generated_rbf_leaf_derivatives(variance, distance, lengthscale, value, dvariance, ddistance, dlengthscale)
    use, intrinsic :: iso_fortran_env, only: real64
    implicit none
    real(real64), intent(in) :: variance, distance, lengthscale
    real(real64), intent(out) :: value, dvariance, ddistance, dlengthscale
    real(real64) :: t5, t8, t9, t10, t11, t13, t15

    t5 = (lengthscale ** (-2.0000000000000000E+000_real64))
    t8 = (distance * t5 * (-1.0000000000000000E+000_real64) * 5.0000000000000000E-001_real64)
    t9 = exp(t8)
    t10 = (variance * t9)
    t11 = (variance * t9 * t5 * (-1.0000000000000000E+000_real64) * 5.0000000000000000E-001_real64)
    t13 = (lengthscale ** (-3.0000000000000000E+000_real64))
    t15 = (distance * variance * t9 * t13 * 2.0000000000000000E+000_real64 * 5.0000000000000000E-001_real64)
    value = t10
    dvariance = t9
    ddistance = t11
    dlengthscale = t15
end subroutine fortml_generated_rbf_leaf_derivatives

