! FortSym IR nodes: 60
! FortSym compound operations: 48
module fortml_generated_matern32_products
    implicit none
contains
    ! Generated by fortsym. Do not edit.
    ! Generator: gen_matern32_hvp
    ! Generator revision: b72a23a
    ! Regenerate with: fo exec gen_matern32_hvp OUTPUT_PATH FORTSYM_REVISION

    subroutine fortml_generated_matern32_hvp_core(distance, distance_d, lv, lv_d, ll, ll_d, y_b, y, y_d, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d)
        use, intrinsic :: iso_fortran_env, only: real64
        implicit none
        real(real64), intent(in) :: distance, distance_d, lv, lv_d, ll, ll_d, y_b
        real(real64), intent(out) :: y, y_d, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d
        real(real64) :: fs_t2, fs_t6, fs_t7, fs_t9, fs_t10, fs_t11, fs_t13, fs_t14, fs_t16, fs_t17, fs_t18, fs_t19, fs_t21, fs_t22, fs_t23, fs_t24, fs_t26, fs_t27, fs_t29, fs_t31, fs_t32, fs_t33, fs_t35, fs_t36, fs_t37, fs_t38, fs_t39, fs_t40, fs_t41, fs_t42, fs_t43, fs_t44, fs_t45, fs_t46, fs_t47, fs_t48, fs_t49, fs_t50, fs_t51, fs_t52, fs_t53, fs_t54, fs_t55, fs_t56, fs_t57, fs_t58, fs_t59, fs_t60

        fs_t2 = exp(lv)
        fs_t6 = (ll * (-1.0000000000000000E+000_real64))
        fs_t7 = exp(fs_t6)
        fs_t9 = (distance * fs_t7 * (-1.0000000000000000E+000_real64) * 1.7320508075688772E+000_real64)
        fs_t10 = exp(fs_t9)
        fs_t11 = (distance * fs_t7 * 1.7320508075688772E+000_real64)
        fs_t13 = (fs_t11 + 1.0000000000000000E+000_real64)
        fs_t14 = (fs_t2 * fs_t10 * fs_t13)
        fs_t16 = (fs_t2 * fs_t10 * fs_t7 * fs_t13 * (-1.0000000000000000E+000_real64) * 1.7320508075688772E+000_real64)
        fs_t17 = (fs_t2 * fs_t10 * fs_t7 * 1.7320508075688772E+000_real64)
        fs_t18 = (fs_t16 + fs_t17)
        fs_t19 = (distance_d * fs_t18)
        fs_t21 = (distance * fs_t2 * fs_t10 * fs_t7 * fs_t13 * 1.7320508075688772E+000_real64)
        fs_t22 = (distance * fs_t2 * fs_t10 * fs_t7 * (-1.0000000000000000E+000_real64) * 1.7320508075688772E+000_real64)
        fs_t23 = (fs_t21 + fs_t22)
        fs_t24 = (ll_d * fs_t23)
        fs_t26 = (lv_d * fs_t2 * fs_t10 * fs_t13)
        fs_t27 = (fs_t19 + fs_t24 + fs_t26)
        fs_t29 = (y_b * fs_t18)
        fs_t31 = (fs_t7 ** 2.0000000000000000E+000_real64)
        fs_t32 = (1.7320508075688772E+000_real64 ** 2.0000000000000000E+000_real64)
        fs_t33 = (fs_t2 * fs_t10 * fs_t31 * fs_t32 * fs_t13)
        fs_t35 = (fs_t2 * fs_t10 * fs_t31 * fs_t32 * (-2.0000000000000000E+000_real64))
        fs_t36 = (fs_t33 + fs_t35)
        fs_t37 = (distance_d * fs_t36)
        fs_t38 = (distance * fs_t2 * fs_t10 * fs_t31 * fs_t32 * fs_t13 * (-1.0000000000000000E+000_real64))
        fs_t39 = (distance * fs_t2 * fs_t10 * fs_t31 * fs_t32 * 2.0000000000000000E+000_real64)
        fs_t40 = (fs_t2 * fs_t10 * fs_t7 * fs_t13 * 1.7320508075688772E+000_real64)
        fs_t41 = (fs_t2 * fs_t10 * fs_t7 * (-1.0000000000000000E+000_real64) * 1.7320508075688772E+000_real64)
        fs_t42 = (fs_t38 + fs_t39 + fs_t40 + fs_t41)
        fs_t43 = (ll_d * fs_t42)
        fs_t44 = (lv_d * fs_t18)
        fs_t45 = (fs_t37 + fs_t43 + fs_t44)
        fs_t46 = (y_b * fs_t45)
        fs_t47 = (y_b * fs_t2 * fs_t10 * fs_t13)
        fs_t48 = (y_b * fs_t27)
        fs_t49 = (y_b * fs_t23)
        fs_t50 = (distance_d * fs_t42)
        fs_t51 = (distance * fs_t2 * fs_t10 * fs_t7 * fs_t13 * (-1.0000000000000000E+000_real64) * 1.7320508075688772E+000_real64)
        fs_t52 = (distance * fs_t2 * fs_t10 * fs_t7 * 1.7320508075688772E+000_real64)
        fs_t53 = (distance ** 2.0000000000000000E+000_real64)
        fs_t54 = (fs_t2 * fs_t10 * fs_t53 * fs_t31 * fs_t32 * fs_t13)
        fs_t55 = (fs_t2 * fs_t10 * fs_t53 * fs_t31 * fs_t32 * (-2.0000000000000000E+000_real64))
        fs_t56 = (fs_t51 + fs_t52 + fs_t54 + fs_t55)
        fs_t57 = (ll_d * fs_t56)
        fs_t58 = (lv_d * fs_t23)
        fs_t59 = (fs_t50 + fs_t57 + fs_t58)
        fs_t60 = (y_b * fs_t59)
        y = fs_t14
        y_d = fs_t27
        distance_b = fs_t29
        distance_b_d = fs_t46
        lv_b = fs_t47
        lv_b_d = fs_t48
        ll_b = fs_t49
        ll_b_d = fs_t60
    end subroutine fortml_generated_matern32_hvp_core

    subroutine fortml_matern32_hvp(distance, distance_d, lv, lv_d, ll, ll_d, y, y_d, &
            y_b, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d)
        use, intrinsic :: iso_fortran_env, only: real64
        implicit none
        real(real64), intent(in) :: distance, distance_d, lv, lv_d, ll, ll_d
        real(real64), intent(out) :: y, y_d
        real(real64), intent(in) :: y_b
        real(real64), intent(out) :: distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d
        call fortml_generated_matern32_hvp_core(distance, distance_d, lv, lv_d, ll, ll_d, y_b, &
            y, y_d, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d)
    end subroutine fortml_matern32_hvp
end module fortml_generated_matern32_products
