! Generated by FortAD. Do not edit.
! Generator: gen_matern_products
! FortAD revision: 5e1bfe0
! Regenerate with: fo exec gen_matern_products OUTPUT_PATH FORTAD_REVISION && fo fmt OUTPUT_PATH
module fortml_generated_matern_products
    implicit none
contains
    pure subroutine fortml_matern12_hvp(distance, distance_d, lv, lv_d, ll, ll_d, y, y_d, &
            y_b, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d)
        implicit none
        real(8), intent(in) :: distance
        real(8), intent(in) :: distance_d
        real(8), intent(in) :: lv
        real(8), intent(in) :: lv_d
        real(8), intent(in) :: ll
        real(8), intent(in) :: ll_d
        real(8), intent(out) :: y
        real(8), intent(out) :: y_d
        real(8), intent(in) :: y_b
        real(8), intent(out) :: distance_b
        real(8), intent(out) :: distance_b_d
        real(8), intent(out) :: lv_b
        real(8), intent(out) :: lv_b_d
        real(8), intent(out) :: ll_b
        real(8), intent(out) :: ll_b_d
        real(8) :: r_v1
        real(8) :: r_v1_d
        real(8) :: y_v1
        real(8) :: r_v1_b
        real(8) :: y_v1_b
        real(8) :: fad_t1
        real(8) :: fad_t1_d
        real(8) :: fad_t2
        real(8) :: fad_t2_d
        real(8) :: fad_t3
        real(8) :: fad_t4
        real(8) :: fad_t5
        real(8) :: fad_t6

        r_v1_d = distance_d * exp(-ll) - distance * exp(-ll) * ll_d
        r_v1 = distance * exp(-ll)
        y_d = exp(lv - r_v1) * (lv_d - r_v1_d)
        y = exp(lv - r_v1)
        fad_t1_d = y_b * (exp(lv - r_v1) * (lv_d - r_v1_d))
        fad_t1 = y_b * exp(lv - r_v1)
        lv_b_d = fad_t1_d
        lv_b = fad_t1
        fad_t2_d = fad_t1_d * (-1.0d0)
        fad_t2 = fad_t1 * (-1.0d0)
        distance_b_d = fad_t2_d * exp(-ll) - fad_t2 * exp(-ll) * ll_d
        distance_b = fad_t2 * exp(-ll)
        ll_b_d = ((fad_t2_d * distance + fad_t2 * distance_d) * exp(-ll) - fad_t2 * &
            distance * exp(-ll) * ll_d) * (-1.0d0)
        ll_b = fad_t2 * distance * exp(-ll) * (-1.0d0)
    end subroutine fortml_matern12_hvp

    pure subroutine fortml_matern32_hvp(distance, distance_d, lv, lv_d, ll, ll_d, y, y_d, &
            y_b, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d)
        implicit none
        real(8), intent(in) :: distance
        real(8), intent(in) :: distance_d
        real(8), intent(in) :: lv
        real(8), intent(in) :: lv_d
        real(8), intent(in) :: ll
        real(8), intent(in) :: ll_d
        real(8), intent(out) :: y
        real(8), intent(out) :: y_d
        real(8), intent(in) :: y_b
        real(8), intent(out) :: distance_b
        real(8), intent(out) :: distance_b_d
        real(8), intent(out) :: lv_b
        real(8), intent(out) :: lv_b_d
        real(8), intent(out) :: ll_b
        real(8), intent(out) :: ll_b_d
        real(8) :: r_v1
        real(8) :: r_v1_d
        real(8) :: y_v1
        real(8) :: r_v1_b
        real(8) :: r_v1_b_d
        real(8) :: y_v1_b
        real(8) :: fad_t1
        real(8) :: fad_t1_d
        real(8) :: fad_t2
        real(8) :: fad_t3
        real(8) :: fad_t4
        real(8) :: fad_t4_d
        real(8) :: fad_t5
        real(8) :: fad_t6
        real(8) :: fad_t7
        real(8) :: fad_t8
        real(8) :: fad_t9
        real(8) :: fad_t10
        real(8) :: fad_t11
        real(8) :: fad_t12

        r_v1_d = sqrt(3.0d0) * distance_d * exp(-ll) - sqrt(3.0d0) * distance * exp(-ll) &
            * ll_d
        r_v1 = sqrt(3.0d0) * distance * exp(-ll)
        y_d = (exp(lv) * lv_d * (1.0d0 + r_v1) + exp(lv) * r_v1_d) * exp(-r_v1) - exp(lv) &
            * (1.0d0 + r_v1) * exp(-r_v1) * r_v1_d
        y = exp(lv) * (1.0d0 + r_v1) * exp(-r_v1)
        fad_t1_d = y_b * (exp(-r_v1) * (-r_v1_d))
        fad_t1 = y_b * exp(-r_v1)
        lv_b_d = (fad_t1_d * (1.0d0 + r_v1) + fad_t1 * r_v1_d) * exp(lv) + fad_t1 * &
            (1.0d0 + r_v1) * (exp(lv) * lv_d)
        lv_b = fad_t1 * (1.0d0 + r_v1) * exp(lv)
        fad_t4_d = fad_t1_d * exp(lv) + fad_t1 * (exp(lv) * lv_d)
        fad_t4 = fad_t1 * exp(lv)
        r_v1_b_d = fad_t4_d
        r_v1_b = fad_t4
        r_v1_b_d = fad_t4_d - ((y_b * (exp(lv) * lv_d) * (1.0d0 + r_v1) + y_b * exp(lv) * &
            r_v1_d) * exp(-r_v1) - y_b * exp(lv) * (1.0d0 + r_v1) * exp(-r_v1) * r_v1_d)
        r_v1_b = fad_t4 - y_b * exp(lv) * (1.0d0 + r_v1) * exp(-r_v1)
        distance_b_d = (r_v1_b_d * exp(-ll) - r_v1_b * exp(-ll) * ll_d) * sqrt(3.0d0)
        distance_b = r_v1_b * exp(-ll) * sqrt(3.0d0)
        ll_b_d = ((r_v1_b_d * (sqrt(3.0d0) * distance) + r_v1_b * (sqrt(3.0d0) * &
            distance_d)) * exp(-ll) - r_v1_b * sqrt(3.0d0) * distance * exp(-ll) * ll_d) * &
            (-1.0d0)
        ll_b = r_v1_b * (sqrt(3.0d0) * distance) * exp(-ll) * (-1.0d0)
    end subroutine fortml_matern32_hvp

    pure subroutine fortml_matern52_hvp(distance, distance_d, lv, lv_d, ll, ll_d, y, y_d, &
            y_b, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d)
        implicit none
        real(8), intent(in) :: distance
        real(8), intent(in) :: distance_d
        real(8), intent(in) :: lv
        real(8), intent(in) :: lv_d
        real(8), intent(in) :: ll
        real(8), intent(in) :: ll_d
        real(8), intent(out) :: y
        real(8), intent(out) :: y_d
        real(8), intent(in) :: y_b
        real(8), intent(out) :: distance_b
        real(8), intent(out) :: distance_b_d
        real(8), intent(out) :: lv_b
        real(8), intent(out) :: lv_b_d
        real(8), intent(out) :: ll_b
        real(8), intent(out) :: ll_b_d
        real(8) :: r_v1
        real(8) :: r_v1_d
        real(8) :: y_v1
        real(8) :: r_v1_b
        real(8) :: r_v1_b_d
        real(8) :: y_v1_b
        real(8) :: fad_t1
        real(8) :: fad_t1_d
        real(8) :: fad_t2
        real(8) :: fad_t3
        real(8) :: fad_t4
        real(8) :: fad_t4_d
        real(8) :: fad_t5
        real(8) :: fad_t6
        real(8) :: fad_t7
        real(8) :: fad_t8
        real(8) :: fad_t9
        real(8) :: fad_t10
        real(8) :: fad_t11
        real(8) :: fad_t12
        real(8) :: fad_t13
        real(8) :: fad_t14

        r_v1_d = sqrt(5.0d0) * distance_d * exp(-ll) - sqrt(5.0d0) * distance * exp(-ll) &
            * ll_d
        r_v1 = sqrt(5.0d0) * distance * exp(-ll)
        y_d = (exp(lv) * lv_d * (1.0d0 + r_v1 + r_v1 * r_v1 / 3.0d0) + exp(lv) * (r_v1_d &
            + 2.0d0 * (r_v1 * r_v1_d) / 3.0d0)) * exp(-r_v1) - exp(lv) * (1.0d0 + r_v1 + r_v1 &
            * r_v1 / 3.0d0) * exp(-r_v1) * r_v1_d
        y = exp(lv) * (1.0d0 + r_v1 + r_v1 * r_v1 / 3.0d0) * exp(-r_v1)
        fad_t1_d = y_b * (exp(-r_v1) * (-r_v1_d))
        fad_t1 = y_b * exp(-r_v1)
        lv_b_d = (fad_t1_d * (1.0d0 + r_v1 + r_v1 * r_v1 / 3.0d0) + fad_t1 * (r_v1_d + &
            2.0d0 * (r_v1 * r_v1_d) / 3.0d0)) * exp(lv) + fad_t1 * (1.0d0 + r_v1 + r_v1 * &
            r_v1 / 3.0d0) * (exp(lv) * lv_d)
        lv_b = fad_t1 * (1.0d0 + r_v1 + r_v1 * r_v1 / 3.0d0) * exp(lv)
        fad_t4_d = fad_t1_d * exp(lv) + fad_t1 * (exp(lv) * lv_d)
        fad_t4 = fad_t1 * exp(lv)
        r_v1_b_d = fad_t4_d
        r_v1_b = fad_t4
        r_v1_b_d = fad_t4_d * (1.0d0 + 1.0d0 / 3.0d0 * 2.0d0 * r_v1) + fad_t4 * (1.0d0 / &
            3.0d0 * 2.0d0 * r_v1_d)
        r_v1_b = fad_t4 * (1.0d0 + 1.0d0 / 3.0d0 * 2.0d0 * r_v1)
        r_v1_b_d = r_v1_b_d - ((y_b * (exp(lv) * lv_d) * (1.0d0 + r_v1 + r_v1 * r_v1 / &
            3.0d0) + y_b * exp(lv) * (r_v1_d + 2.0d0 * (r_v1 * r_v1_d) / 3.0d0)) * exp(-r_v1) &
            - y_b * exp(lv) * (1.0d0 + r_v1 + r_v1 * r_v1 / 3.0d0) * exp(-r_v1) * r_v1_d)
        r_v1_b = r_v1_b - y_b * exp(lv) * (1.0d0 + r_v1 + r_v1 * r_v1 / 3.0d0) * exp(-r_v1)
        distance_b_d = (r_v1_b_d * exp(-ll) - r_v1_b * exp(-ll) * ll_d) * sqrt(5.0d0)
        distance_b = r_v1_b * exp(-ll) * sqrt(5.0d0)
        ll_b_d = ((r_v1_b_d * (sqrt(5.0d0) * distance) + r_v1_b * (sqrt(5.0d0) * &
            distance_d)) * exp(-ll) - r_v1_b * sqrt(5.0d0) * distance * exp(-ll) * ll_d) * &
            (-1.0d0)
        ll_b = r_v1_b * (sqrt(5.0d0) * distance) * exp(-ll) * (-1.0d0)
    end subroutine fortml_matern52_hvp

end module fortml_generated_matern_products
