! FortSym IR nodes: 37
! FortSym compound operations: 28
module fortml_generated_matern12_products
    implicit none
contains
    ! Generated by fortsym. Do not edit.
    ! Generator: gen_matern12_hvp
    ! Generator revision: 9482261
    ! Regenerate with: fo exec gen_matern12_hvp OUTPUT_PATH FORTSYM_REVISION

    subroutine fortml_generated_matern12_hvp_core(distance, distance_d, lv, lv_d, ll, ll_d, y_b, y, y_d, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d)
        use, intrinsic :: iso_fortran_env, only: real64
        implicit none
        real(real64), intent(in) :: distance, distance_d, lv, lv_d, ll, ll_d, y_b
        real(real64), intent(out) :: y, y_d, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d
        real(real64) :: fs_t5, fs_t6, fs_t7, fs_t8, fs_t9, fs_t11, fs_t13, fs_t15, fs_t16, fs_t18, fs_t20, fs_t21, fs_t22, fs_t23, fs_t24, fs_t25, fs_t26, fs_t27, fs_t28, fs_t29, fs_t30, fs_t31, fs_t32, fs_t33, fs_t34, fs_t35, fs_t36, fs_t37

        fs_t5 = (ll * (-1.0000000000000000E+000_real64))
        fs_t6 = exp(fs_t5)
        fs_t7 = (distance * fs_t6 * (-1.0000000000000000E+000_real64))
        fs_t8 = (lv + fs_t7)
        fs_t9 = exp(fs_t8)
        fs_t11 = (distance * ll_d * fs_t6 * fs_t9)
        fs_t13 = (distance_d * fs_t6 * fs_t9 * (-1.0000000000000000E+000_real64))
        fs_t15 = (lv_d * fs_t9)
        fs_t16 = (fs_t11 + fs_t13 + fs_t15)
        fs_t18 = (y_b * fs_t6 * fs_t9 * (-1.0000000000000000E+000_real64))
        fs_t20 = (fs_t6 ** 2.0000000000000000E+000_real64)
        fs_t21 = (distance * ll_d * fs_t9 * fs_t20 * (-1.0000000000000000E+000_real64))
        fs_t22 = (distance_d * fs_t9 * fs_t20)
        fs_t23 = (ll_d * fs_t6 * fs_t9)
        fs_t24 = (lv_d * fs_t6 * fs_t9 * (-1.0000000000000000E+000_real64))
        fs_t25 = (fs_t21 + fs_t22 + fs_t23 + fs_t24)
        fs_t26 = (y_b * fs_t25)
        fs_t27 = (y_b * fs_t9)
        fs_t28 = (y_b * fs_t16)
        fs_t29 = (distance * y_b * fs_t6 * fs_t9)
        fs_t30 = (distance * distance_d * fs_t9 * fs_t20 * (-1.0000000000000000E+000_real64))
        fs_t31 = (distance * ll_d * fs_t6 * fs_t9 * (-1.0000000000000000E+000_real64))
        fs_t32 = (distance * lv_d * fs_t6 * fs_t9)
        fs_t33 = (distance_d * fs_t6 * fs_t9)
        fs_t34 = (distance ** 2.0000000000000000E+000_real64)
        fs_t35 = (ll_d * fs_t9 * fs_t34 * fs_t20)
        fs_t36 = (fs_t30 + fs_t31 + fs_t32 + fs_t33 + fs_t35)
        fs_t37 = (y_b * fs_t36)
        y = fs_t9
        y_d = fs_t16
        distance_b = fs_t18
        distance_b_d = fs_t26
        lv_b = fs_t27
        lv_b_d = fs_t28
        ll_b = fs_t29
        ll_b_d = fs_t37
    end subroutine fortml_generated_matern12_hvp_core

    subroutine fortml_matern12_hvp(distance, distance_d, lv, lv_d, ll, ll_d, y, y_d, &
            y_b, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d)
        use, intrinsic :: iso_fortran_env, only: real64
        implicit none
        real(real64), intent(in) :: distance, distance_d, lv, lv_d, ll, ll_d
        real(real64), intent(out) :: y, y_d
        real(real64), intent(in) :: y_b
        real(real64), intent(out) :: distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d
        call fortml_generated_matern12_hvp_core(distance, distance_d, lv, lv_d, ll, ll_d, y_b, &
            y, y_d, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d)
    end subroutine fortml_matern12_hvp
end module fortml_generated_matern12_products
