! Generated by fortsym. Do not edit.
! Generator: gen_rbf_leaf
! Generator revision: 16fc3a8
! Regenerate with: fo exec gen_rbf_leaf OUTPUT_PATH FORTSYM_REVISION

subroutine fortml_generated_rbf_leaf_fortran(variance, distance, lengthscale, output)
    use, intrinsic :: iso_fortran_env, only: real64
    implicit none
    real(real64), intent(in) :: variance, distance, lengthscale
    real(real64), intent(out) :: output
    real(real64) :: t5, t8, t9, t10

    t5 = (lengthscale ** (-2.0000000000000000E+000_real64))
    t8 = (distance * t5 * (-1.0000000000000000E+000_real64) * 5.0000000000000000E-001_real64)
    t9 = exp(t8)
    t10 = (variance * t9)
    output = t10
end subroutine fortml_generated_rbf_leaf_fortran

