! FortSym IR nodes: 80
! FortSym compound operations: 65
module fortml_generated_matern52_products
    implicit none
contains
    ! Generated by fortsym. Do not edit.
    ! Generator: gen_matern52_hvp
    ! Generator revision: 873d33f
    ! Regenerate with: fo exec gen_matern52_hvp OUTPUT_PATH FORTSYM_REVISION

    subroutine fortml_generated_matern52_hvp_core(distance, distance_d, lv, lv_d, ll, ll_d, y_b, y, y_d, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d)
        use, intrinsic :: iso_fortran_env, only: real64
        implicit none
        real(real64), intent(in) :: distance, distance_d, lv, lv_d, ll, ll_d, y_b
        real(real64), intent(out) :: y, y_d, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d
        real(real64) :: fs_t2, fs_t6, fs_t7, fs_t9, fs_t10, fs_t11, fs_t13, fs_t14, fs_t16, fs_t18, fs_t20, fs_t22, fs_t23, fs_t25, fs_t26, fs_t27, fs_t28, fs_t29, fs_t30, fs_t31, fs_t33, fs_t34, fs_t35, fs_t36, fs_t37, fs_t38, fs_t40, fs_t41, fs_t43, fs_t45, fs_t46, fs_t47, fs_t48, fs_t49, fs_t50, fs_t51, fs_t52, fs_t53, fs_t54, fs_t55, fs_t56, fs_t57, fs_t58, fs_t59, fs_t60, fs_t61, fs_t62, fs_t63, fs_t64, fs_t65, fs_t66, fs_t67, fs_t68, fs_t69, fs_t70, fs_t71, fs_t72, fs_t73, fs_t74, fs_t75, fs_t76, &
            fs_t77, fs_t78, fs_t79, fs_t80

        fs_t2 = exp(lv)
        fs_t6 = (ll * (-1.0000000000000000E+000_real64))
        fs_t7 = exp(fs_t6)
        fs_t9 = (distance * fs_t7 * (-1.0000000000000000E+000_real64) * 2.2360679774997898E+000_real64)
        fs_t10 = exp(fs_t9)
        fs_t11 = (distance * fs_t7 * 2.2360679774997898E+000_real64)
        fs_t13 = (ll * (-1.0000000000000000E+000_real64) * 2.0000000000000000E+000_real64)
        fs_t14 = exp(fs_t13)
        fs_t16 = (distance ** 2.0000000000000000E+000_real64)
        fs_t18 = (3.0000000000000000E+000_real64 ** (-1.0000000000000000E+000_real64))
        fs_t20 = (fs_t14 * fs_t16 * fs_t18 * 5.0000000000000000E+000_real64)
        fs_t22 = (fs_t11 + fs_t20 + 1.0000000000000000E+000_real64)
        fs_t23 = (fs_t2 * fs_t10 * fs_t22)
        fs_t25 = (fs_t2 * fs_t10 * fs_t7 * fs_t22 * (-1.0000000000000000E+000_real64) * 2.2360679774997898E+000_real64)
        fs_t26 = (distance * fs_t14 * fs_t18 * 2.0000000000000000E+000_real64 * 5.0000000000000000E+000_real64)
        fs_t27 = (fs_t7 * 2.2360679774997898E+000_real64)
        fs_t28 = (fs_t26 + fs_t27)
        fs_t29 = (fs_t2 * fs_t10 * fs_t28)
        fs_t30 = (fs_t25 + fs_t29)
        fs_t31 = (distance_d * fs_t30)
        fs_t33 = (distance * fs_t2 * fs_t10 * fs_t7 * fs_t22 * 2.2360679774997898E+000_real64)
        fs_t34 = (fs_t14 * fs_t16 * fs_t18 * (-1.0000000000000000E+000_real64) * 2.0000000000000000E+000_real64 * 5.0000000000000000E+000_real64)
        fs_t35 = (fs_t9 + fs_t34)
        fs_t36 = (fs_t2 * fs_t10 * fs_t35)
        fs_t37 = (fs_t33 + fs_t36)
        fs_t38 = (ll_d * fs_t37)
        fs_t40 = (lv_d * fs_t2 * fs_t10 * fs_t22)
        fs_t41 = (fs_t31 + fs_t38 + fs_t40)
        fs_t43 = (y_b * fs_t30)
        fs_t45 = (fs_t2 * fs_t10 * fs_t7 * fs_t28 * (-2.0000000000000000E+000_real64) * 2.2360679774997898E+000_real64)
        fs_t46 = (fs_t2 * fs_t10 * fs_t14 * fs_t18 * 2.0000000000000000E+000_real64 * 5.0000000000000000E+000_real64)
        fs_t47 = (fs_t7 ** 2.0000000000000000E+000_real64)
        fs_t48 = (2.2360679774997898E+000_real64 ** 2.0000000000000000E+000_real64)
        fs_t49 = (fs_t2 * fs_t10 * fs_t47 * fs_t48 * fs_t22)
        fs_t50 = (fs_t45 + fs_t46 + fs_t49)
        fs_t51 = (distance_d * fs_t50)
        fs_t52 = (distance * fs_t2 * fs_t10 * fs_t7 * fs_t28 * 2.2360679774997898E+000_real64)
        fs_t53 = (distance * fs_t2 * fs_t10 * fs_t47 * fs_t48 * fs_t22 * (-1.0000000000000000E+000_real64))
        fs_t54 = (fs_t2 * fs_t10 * fs_t7 * fs_t35 * (-1.0000000000000000E+000_real64) * 2.2360679774997898E+000_real64)
        fs_t55 = (fs_t2 * fs_t10 * fs_t7 * fs_t22 * 2.2360679774997898E+000_real64)
        fs_t56 = (distance * fs_t14 * fs_t18 * (-2.0000000000000000E+000_real64) * 2.0000000000000000E+000_real64 * 5.0000000000000000E+000_real64)
        fs_t57 = (fs_t7 * (-1.0000000000000000E+000_real64) * 2.2360679774997898E+000_real64)
        fs_t58 = (fs_t56 + fs_t57)
        fs_t59 = (fs_t2 * fs_t10 * fs_t58)
        fs_t60 = (fs_t52 + fs_t53 + fs_t54 + fs_t55 + fs_t59)
        fs_t61 = (ll_d * fs_t60)
        fs_t62 = (lv_d * fs_t30)
        fs_t63 = (fs_t51 + fs_t61 + fs_t62)
        fs_t64 = (y_b * fs_t63)
        fs_t65 = (y_b * fs_t2 * fs_t10 * fs_t22)
        fs_t66 = (y_b * fs_t41)
        fs_t67 = (y_b * fs_t37)
        fs_t68 = (distance_d * fs_t60)
        fs_t69 = (distance * fs_t2 * fs_t10 * fs_t7 * fs_t35 * 2.0000000000000000E+000_real64 * 2.2360679774997898E+000_real64)
        fs_t70 = (distance * fs_t2 * fs_t10 * fs_t7 * fs_t22 * (-1.0000000000000000E+000_real64) * 2.2360679774997898E+000_real64)
        fs_t71 = (fs_t2 * fs_t10 * fs_t16 * fs_t47 * fs_t48 * fs_t22)
        fs_t72 = (2.0000000000000000E+000_real64 ** 2.0000000000000000E+000_real64)
        fs_t73 = (fs_t14 * fs_t16 * fs_t72 * fs_t18 * 5.0000000000000000E+000_real64)
        fs_t74 = (fs_t11 + fs_t73)
        fs_t75 = (fs_t2 * fs_t10 * fs_t74)
        fs_t76 = (fs_t69 + fs_t70 + fs_t71 + fs_t75)
        fs_t77 = (ll_d * fs_t76)
        fs_t78 = (lv_d * fs_t37)
        fs_t79 = (fs_t68 + fs_t77 + fs_t78)
        fs_t80 = (y_b * fs_t79)
        y = fs_t23
        y_d = fs_t41
        distance_b = fs_t43
        distance_b_d = fs_t64
        lv_b = fs_t65
        lv_b_d = fs_t66
        ll_b = fs_t67
        ll_b_d = fs_t80
    end subroutine fortml_generated_matern52_hvp_core

    subroutine fortml_matern52_hvp(distance, distance_d, lv, lv_d, ll, ll_d, y, y_d, &
            y_b, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d)
        use, intrinsic :: iso_fortran_env, only: real64
        implicit none
        real(real64), intent(in) :: distance, distance_d, lv, lv_d, ll, ll_d
        real(real64), intent(out) :: y, y_d
        real(real64), intent(in) :: y_b
        real(real64), intent(out) :: distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d
        call fortml_generated_matern52_hvp_core(distance, distance_d, lv, lv_d, ll, ll_d, y_b, &
            y, y_d, distance_b, distance_b_d, lv_b, lv_b_d, ll_b, ll_b_d)
    end subroutine fortml_matern52_hvp
end module fortml_generated_matern52_products
