/* Generated by fortsym. Do not edit. */
// Generator: test_fortsym_kernel_emit
// Generator revision: 56b4fe0
// Regenerate from: variance*exp(-0.5*distance*lengthscale**(-2))
// Regeneration contract: FortSym kernel_emit_spec_t / emit_cuda_device_ir

#include <math.h>

extern "C" __device__ __forceinline__
void fortml_generated_rbf_leaf(const double variance, const double distance,
                               const double lengthscale, double* output) {
  const double t5 = pow(lengthscale, (-2.0000000000000000E+000));
  const double t7 = (distance * t5 * (-5.0000000000000000E-001));
  const double t8 = exp(t7);
  const double t9 = (variance * t8);
  *output = t9;
}
